# Project Name does not contain space
PROJECT_NAME=GLI_Test
PROJECT_TITLE=GLI Test
PROJECT_ID=com.gli.test
VERSION_NAME=1.0.0
VERSION_CODE=1
COMPILE_SDK=36
MINIMUM_SDK=24
TARGET_SDK=36
JAVA_VERSION=17